easybook:
    parameters:
        kindlegen.path: '/home/sopra/kindlegen/kindlegen'
        kindlegen.command_options: '-c0 verbose'
        parser.options:
            code_block_type: github

book:
    title:            "Blog Cosillas de Juansal"
    author:           "Juan Salvador Aleixandre"
    edition:          "First edition"
    language:         es
    publication_date: ~

    generator: { name: easybook, version: 4.9.0 }

    contents:
        # available content types: acknowledgement, afterword, appendix, author,
        # chapter, conclusion, cover, dedication, edition, epilogue, foreword,
        # glossary, introduction, license, lof (list of figures), lot (list of
        # tables), part, preface, prologue, title, toc (table of contents)
        - { element: cover }
        - { element: toc   }
        - { element: chapter, number: 1, content: README.md }
        - { element: chapter, number: 2, content: 2010/README.md }
        - { element: chapter, number: 2.1, content: 2010/presentacion.md }
        - { element: chapter, number: 2.2, content: 2010/migracion_de_rx_components_a_jvcl_i.md }
        - { element: chapter, number: 2.3, content: 2010/migracion_de_rx_components_a_jvcl_0.md }
        - { element: chapter, number: 2.4, content: 2010/activar_la_cuenta_root_en_ubuntu.md }
        - { element: chapter, number: 2.5, content: 2010/reseteo_del_id_y_de_la_mac_de_una_maquina_virtual_en_vmware.md }
        - { element: chapter, number: 2.6, content: 2010/hacer_que_el_vmware_utilice_la_memoria_fisica_y_no_un_fichero_en_una_maquina_virtual.md }
        - { element: chapter, number: 2.7, content: 2010/crear_un_mirror_de_un_repositorio_de_subversion.md }
        - { element: chapter, number: 2.8, content: 2010/lectura_de_ficheros_ini_sin_secciones_con_inno_setup_desde_codigo.md }
        - { element: chapter, number: 2.9, content: 2010/lectura_de_ficheros_ini_sin_secciones_con_inno_setup_desde_codigo_continuacion.md }
        - { element: chapter, number: 2.10, content: 2010/desactivacion_de_unity_de_las_maquinas_virtuales_de_vmware_workstation.md }
        - { element: chapter, number: 3, content: 2011/README.md }
        - { element: chapter, number: 3.1, content: 2011/plugin_de_firefox.md }
        - { element: chapter, number: 3.2, content: 2011/cambiar_el_propietario_y_el_grupo_al_que_pertenece_un_fichero_o_una_carpeta_en_linux.md }
        - { element: chapter, number: 3.3, content: 2011/obtener_informacion_de_la_maquina_y_del_windows_instalado_en_ella_desde_linea_de_comandos.md }
        - { element: chapter, number: 4, content: 2012/README.md }
        - { element: chapter, number: 4.1, content: 2012/conversion_de_disco_virtual_de_virtualbox_a_vmware.md }
        - { element: chapter, number: 4.2, content: 2012/forzar_a_un_maquina_virtual_de_vmware_a_usar_un_adaptador_de_red_especifico.md }
        - { element: chapter, number: 4.3, content: 2013/README.md }
        - { element: chapter, number: 4.4, content: 2013/log4net_con_c.md }
        - { element: chapter, number: 4.5, content: 2013/log4net_con_vbnet.md }
        - { element: chapter, number: 4.6, content: 2013/log4java_en_java.md }
        - { element: chapter, number: 4.7, content: 2013/como_obtener_el_id_autogenerado_al_realizar_un_insert_en_una_base_de_datos.md }
        - { element: chapter, number: 4.8, content: 2013/mozilla_add-on_builder_posibilidades_a_la_hora_de_abrir_un_link_desde_una_entrada_de_menu.md }
        - { element: chapter, number: 4.9, content: 2013/mis_primeras_impresiones_con_ouya.md }
        - { element: chapter, number: 5, content: 2014/README.md }
        - { element: chapter, number: 5.1, content: 2014/lineas_minimas_a_anadir_al_codigo_del_industruino_para_usar_las_librerias_m2tklib.md }
        - { element: chapter, number: 5.2, content: 2014/pasos_seguidos_para_crear_un_sistema_de_backup_online_usando_el_bittorrent_y_una_cubietruck_cubieboard_3.md }
        - { element: chapter, number: 5.3, content: 2014/informacion_sobre_temperatura_y_discos_duros_en_la_cubietruck_cubieboard_3.md }
        - { element: chapter, number: 6, content: 2015/README.md }
        - { element: chapter, number: 6.1, content: 2015/markdown.md }
        - { element: chapter, number: 6.2, content: 2015/maquina_virtual_para_trabajar_con_documentos_en_markdown.md }
        - { element: chapter, number: 6.3, content: 2015/anadir_a_un_usuario_los_permisos_de_sudo_en_fedora.md }
        - { element: chapter, number: 6.4, content: 2015/instalacion_y_primeros_pasos_con_haroopress.md }
        - { element: chapter, number: 6.5, content: 2015/formato_de_datos_de_haroopress.md }
        - { element: chapter, number: 6.6, content: 2015/web_con_informacion_sobre_temperatura_y_discos_duros_en_la_cubietruck_cubieboard_3.md }
        - { element: chapter, number: 6.7, content: 2015/organizar_fotos_por_fecha_usando_zoner_photo_studio.md }
        - { element: chapter, number: 6.8, content: 2015/construccion_de_maquina_recreativa_-_introduccion.md }
        - { element: chapter, number: 6.9, content: 2015/construccion_de_maquina_recreativa_-_mueble_-_construccion_del_mueble.md }
        - { element: chapter, number: 6.10, content: 2015/construccion_de_maquina_recreativa_-_mueble_-_entrada_de_alimentacion_y_ventilacion.md }
        - { element: chapter, number: 6.11, content: 2015/construccion_de_maquina_recreativa_-_mueble_-_cableado.md }
        - { element: chapter, number: 6.12, content: 2015/construccion_de_maquina_recreativa_-_mueble_-_botones_de_encendido_y_apagado_de_la_maquina.md }
        - { element: chapter, number: 6.13, content: 2015/construccion_de_maquina_recreativa_-_mueble_-_bezel.md }
        - { element: chapter, number: 6.14, content: 2015/construccion_de_maquina_recreativa_-_el_video.md }
        - { element: chapter, number: 6.15, content: 2015/construccion_de_maquina_recreativa_-_los_controles.md }
        - { element: chapter, number: 6.16, content: 2015/construccion_de_maquina_recreativa_-_el_sonido.md }
        - { element: chapter, number: 6.17, content: 2015/construccion_de_maquina_recreativa_-_agradecimientos.md }
        - { element: chapter, number: 6.18, content: 2015/sistema_de_apertura_de_un_escaparate_con_arduino.md }
        - { element: chapter, number: 7, content: 2016/README.md }
        - { element: chapter, number: 7.1, content: 2016/maquina_virtual_para_trabajar_con_documentos_en_markdown_-_nueva_version.md }
        - { element: chapter, number: A.0, content: secciones_adicionales/README.md }
        - { element: chapter, number: A.1, content: secciones_adicionales/links_interesantes.md }
        - { element: chapter, number: A.2, content: secciones_adicionales/plugins_de_firefox.md }
        - { element: chapter, number: A.3, content: secciones_adicionales/documentos_compartidos.md }
        - { element: chapter, number: A.4, content: secciones_adicionales/proyectos.md }
        - { element: lof   }

    editions:
        ebook:
            format:         epub
            highlight_code: true
            include_styles: true
            labels:         ['appendix', 'chapter']  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       1
                elements:   ["appendix", "chapter", "part"]

        kindle:
            extends:        ebook
            format:         mobi

        print:
            format:         pdf
            highlight_code: true
            include_styles: true
            isbn:           ~
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outer:      20mm
            page_size:      A4
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter", "part"]
            two_sided:      true

        web:
            format:         html
            highlight_code: true
            include_styles: true
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter"]

        website:
            extends:        web
            format:         html_chunked
                            
